import { readText } from "./file-utils.js";
import type { DiffAnalysis, DiffMetrics } from "./types.js";

export interface AiAdapter {
  generateInitial(input: {
    imagePath: string;
    promptPath: string;
  }): Promise<{ html: string; css: string }>;

  analyzeDiff(input: {
    imagePath: string;
    renderPath: string;
    diffPath: string;
    metrics: DiffMetrics;
    promptPath: string;
  }): Promise<DiffAnalysis>;

  reviseCode(input: {
    html: string;
    css: string;
    analysis: DiffAnalysis;
    promptPath: string;
  }): Promise<{ html: string; css: string }>;
}

export class MockAiAdapter implements AiAdapter {
  async generateInitial(input: {
    imagePath: string;
    promptPath: string;
  }): Promise<{ html: string; css: string }> {
    await readText(input.promptPath);
    const html = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Generated Landing Page</title>
    <link rel="stylesheet" href="styles.css" />
  </head>
  <body>
    <main class="page">
      <section class="hero">
        <p class="eyebrow">AUTOGENERATED</p>
        <h1>Landing Page Draft</h1>
        <p class="lead">Replace this structure iteratively based on visual diff analysis.</p>
        <a href="#" class="cta">Call to Action</a>
      </section>
    </main>
  </body>
</html>
`;
    const css = `:root {
  --bg: #f6f7fb;
  --text: #1c2230;
  --muted: #616b7e;
  --accent: #2962ff;
}

* {
  box-sizing: border-box;
}

html,
body {
  margin: 0;
  padding: 0;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  color: var(--text);
  background: var(--bg);
}

.page {
  min-height: 100vh;
  display: grid;
  place-items: center;
  padding: 56px 24px;
}

.hero {
  max-width: 900px;
  text-align: center;
  background: #fff;
  border-radius: 16px;
  padding: 72px 56px;
  box-shadow: 0 20px 40px rgba(17, 24, 39, 0.08);
}

.eyebrow {
  letter-spacing: 0.12em;
  font-size: 12px;
  color: var(--muted);
  margin: 0 0 12px;
}

h1 {
  margin: 0;
  font-size: 48px;
  line-height: 1.1;
}

.lead {
  margin: 20px auto 0;
  max-width: 56ch;
  line-height: 1.7;
  color: var(--muted);
}

.cta {
  margin-top: 28px;
  display: inline-block;
  padding: 12px 22px;
  border-radius: 10px;
  text-decoration: none;
  color: #fff;
  background: var(--accent);
  font-weight: 600;
}
`;
    return { html, css };
  }

  async analyzeDiff(input: {
    imagePath: string;
    renderPath: string;
    diffPath: string;
    metrics: DiffMetrics;
    promptPath: string;
  }): Promise<DiffAnalysis> {
    await readText(input.promptPath);
    const severity: "low" | "medium" | "high" =
      input.metrics.diffRatio > 0.2 ? "high" : input.metrics.diffRatio > 0.1 ? "medium" : "low";

    return {
      summary: `Visual diff ratio is ${input.metrics.diffRatio.toFixed(4)}.`,
      issues: [
        {
          category: "layout-proportion",
          severity,
          description: "Overall proportions do not match the source design.",
          suggestedAction: "Adjust section dimensions and spacing scale."
        },
        {
          category: "alignment",
          severity,
          description: "Primary content alignment differs from source.",
          suggestedAction: "Tune container width and horizontal alignment."
        },
        {
          category: "color",
          severity,
          description: "Detected color mismatch in major surfaces.",
          suggestedAction: "Refine background and text color values."
        }
      ]
    };
  }

  async reviseCode(input: {
    html: string;
    css: string;
    analysis: DiffAnalysis;
    promptPath: string;
  }): Promise<{ html: string; css: string }> {
    await readText(input.promptPath);
    const highIssueCount = input.analysis.issues.filter((issue) => issue.severity === "high").length;

    let nextCss = input.css;
    if (highIssueCount > 0 && !input.css.includes("--iteration-tweak")) {
      nextCss += `\n:root {\n  --iteration-tweak: 1;\n}\n`;
    }

    return { html: input.html, css: nextCss };
  }
}

export function createAiAdapter(): AiAdapter {
  return new MockAiAdapter();
}
